# Generated by Django 5.2.5 on 2025-09-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'permissions': [('can_delete_user', 'Can delete user'), ('can_view_user', 'Can view user'), ('can_add_room', 'Can add room'), ('can_edit_room', 'Can edit room'), ('can_delete_room', 'Can delete room'), ('can_view_room', 'Can view room'), ('can_add_booking', 'Can add booking'), ('can_edit_booking', 'Can edit booking'), ('can_delete_booking', 'Can delete booking'), ('can_view_booking', 'Can view booking'), ('can_add_role', 'Can add role'), ('can_delete_role', 'Can delete role'), ('can_view_role', 'Can view role')],
            },
        ),
    ]
