# Generated by Django 5.2.5 on 2025-09-05 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': [('can_delete_user', 'Can delete user'), ('can_view_user', 'Can view user')]},
        ),
    ]
