# Generated by Django 5.2.5 on 2025-09-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_permissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': [('can_delete_user', 'Can delete user'), ('can_view_user', 'Can view user'), ('can_add_room', 'Can add room'), ('can_edit_room', 'Can edit room'), ('can_delete_room', 'Can delete room'), ('can_view_room', 'Can view room'), ('can_add_booking', 'Can add booking'), ('can_edit_booking', 'Can edit booking'), ('can_delete_booking', 'Can delete booking'), ('can_view_booking', 'Can view booking'), ('can_add_role', 'Can add role'), ('can_delete_role', 'Can delete role'), ('can_view_role', 'Can view role')]},
        ),
    ]
