# Generated by Django 5.2.5 on 2025-09-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100, unique=True)),
                ('room_capacity', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('status', models.IntegerField()),
                ('price_per_night', models.IntegerField()),
                ('features', models.JSONField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
