# Generated by Django 5.2.5 on 2025-10-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_number',
            new_name='room',
        ),
    ]
